### ISSUE TITLE
Add "uses" for Marks

### ISSUE THREAD

**Issue by alyip98** [CS2103-AY1819S1-W13-3/main#59]
For other features such as attendance, edit, delete, email etc, implement the IMarkExecutable interface if the feature is supports execution with marks (e.g. batch attendance updating, batch emailing)

@preethi-d suggested format for `email`:
```
email m/MARK b/BODY
```

@yogtew suggested format for `attendance`:
```
attendance m/MARK at/ATTENDANCE
```

Suggested implementation details:
1. Update `YourCommandParser` to accept a `PREFIX_MARK` in the tokenizer
2. Check if `argumentMultiMap` contains a value for the `PREFIX_MARK` attribute
3. If present, call `executeMark` method from `execute` and return the `CommandResult` from that
4. Otherwise, run the rest of `execute` as normal

Can refer to the `SetTagCommand` for inspiration

**Comment by alyip98** [comment]
I can write or you write also can haha

**Comment by yogtew** [comment]
what is this about?

**Comment by alyip98** [comment]
Implement the interface to allow your command to be run with a Mark

**Comment by alyip98** [comment]
added tag command

**Comment by alyip98** [comment]
#131
