### ISSUE TITLE
`schedule` command issues

### ISSUE THREAD

**Issue by FongYuan** [CS2103-AY1819S1-W13-3/main#97]
Hello W13-3, I was one of your reviewers for the PE Dry Run but I did not submit my issues to the private repo, so I'm submitting them here instead. (https://github.com/nus-cs2103-AY1819S1/forum/issues/144) Thank you for bearing with me.
Now for the actual issue itself:

The `schedule` command has the following sub-issues:

- The example in the user guide does not use the `event/` prefix, does not have the `:` in the start and times, and does not have the description field. The example command is rejected as invalid in the app.
- When I enter an invalid event name (e.g. empty name), it is feedbacked that "Event names should only contain alphanumeric characters and spaces", but the "event" parameter accepts characters such as `^` and `,`
- The "date" field is specified to be "formatted as dd/mm/yyyy, dd-mm-yyyy, or dd.mm.yyyy", but `01.01.1999` and `01/01/1999` are invalid dates.
- The date is only accepted if the year is 1600 or later. This restriction was not mentioned in the command help or user guide.
- The description field "should only contain alphanumeric characters and spaces" as well, but it accepts `^`

**Comment by andrewtanJS** [comment]
Hi @FongYuan, thanks for pointing these out! I'll look into these at once.

**Comment by andrewtanJS** [comment]
updated - resolved #102
